version: '3'
networks:
    service:
    secured:

services:
    rsyslog:
        build:
            context: ./docker-rsyslog
        networks:
            - service
        ports:
            - "514:514"
        volumes:
            - ./docker-rsyslog/app:/app
        env_file: .env
        hostname: rsyslog
        restart: always

    mail2url:
        build:
            context: ./docker-mail2url
        networks:
            - service
        ports:
            - "25:25"
        volumes:
            - ./docker-mail2url/app:/app
        env_file: .env
        hostname: mail2url
        restart: always

    web:
        build:
            context: ./docker-web
        networks:
            - service
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker-web/app:/app
            - ./docker-web/certs/ssl:/etc/ssl/acme
            - ./docker-web/certs/acme:/etc/acme
        env_file: .env
        hostname: web
        restart: always

    homebridge:
        build:
            context: ./docker-homebridge
        network_mode: host
        ports:
            - "5353:5353"
            - "51827:51827"
        volumes:
            - ./docker-homebridge/app:/app
        env_file: .env
        restart: always

    homekit2mqtt:
        build:
            context: ./docker-homekit2mqtt
        network_mode: host
        ports:
            - "5353:5353"
            - "51827:51827"
        volumes:
            - ./docker-homekit2mqtt/app:/app
        env_file: .env
        restart: always

    vpn:
        build:
            context: ./docker-vpn
        network_mode: host
        cap_add:
            - NET_ADMIN
        privileged: true
        volumes:
            - ./docker-vpn/app:/app
        env_file: .env
        restart: always

    socks:
        image: "xkuma/socks5"
        networks:
            - secured
        ports:
            - "1080:1080"
        env_file: .env
        hostname: socks
        restart: always
